apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mimir.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - --default-mimir-image={{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
            - --enable-webhook={{ .Values.webhook.enabled }}
            {{- if .Values.webhook.enabled }}
            - --webhook-cert-dir=/tmp/k8s-webhook-server/serving-certs
            {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
            {{- if .Values.webhook.enabled }}
            - name: webhook
              containerPort: 9443
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
          {{- if .Values.webhook.enabled }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          {{- end }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "mimir.fullname" . }}-webhook-tls
      {{- end }}
