apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backupschedules.mimir.io
spec:
  group: mimir.io
  scope: Namespaced
  names:
    plural: backupschedules
    singular: backupschedule
    kind: BackupSchedule
    shortNames:
      - bs
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [namespace, schedule, storageBackend]
              properties:
                namespace:
                  type: string
                schedule:
                  type: string
                storageBackend:
                  type: string
                  enum: [s3, azure, gcs]
                storageSecret:
                  type: string
                pvcs:
                  type: array
                  items:
                    type: string
                image:
                  type: string
            status:
              type: object
              properties:
                cronJob:
                  type: string
                conditions:
                  type: array
                  x-kubernetes-list-map-keys: [type]
                  x-kubernetes-list-type: map
                  items:
                    type: object
                    required: [type, status, lastTransitionTime, reason]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      observedGeneration:
                        type: integer
                        format: int64
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
